### ISSUE TITLE
User not found on LDAP

### ISSUE THREAD

**Issue by henry-geronimo** [DarwinOnLine/DoLLdapBundle#2]
Hi, i'm trying to go from FR3DLdapBundle, to your Bundle but even if i keep the same config with only one domain, it keeps telling me my user is not Found whereas everything is working using FR3DLdapBundle, did i miss something ?

my config:

```
dol_ldap:
    domains:
        server1:
            driver:
                host: '%ldap_host%'
                username: '%ldap_user%'
                password: '%ldap_password%'
            user:
                baseDn: '%ldap_base_dn%'
                filter: (&(ObjectClass=person))
                usernameAttribute: sAMAccountName
    service:
        user_hydrator: app.ldap.user_hydrator
```

logs: 

> [2017-09-19 08:38:52] security.INFO: User test-user not found on LDAP {"action":"loadUserByUsername","username":"test-user","result":"not found"} {"url":"/api/login_check","ip":"127.0.0.1","http_method":"POST","server":"127.0.0.1","referrer":null}
[2017-09-19 08:38:52] security.INFO: User test-user not found on LDAP {"action":"loadUserByUsername","username":"test-user","result":"not found"} {"url":"/api/login_check","ip":"127.0.0.1","http_method":"POST","server":"127.0.0.1","referrer":null}

**Comment by DarwinOnLine** [comment]
Hello @henry-geronimo, perhaps your configuration is a little too light ?

For example :
```
dol_ldap:
    domains:
        server1:
            driver:
                host:                   "%ldap_driver_host%"
                port:                   "%ldap_driver_port%"
                username:               "%ldap_driver_username%"
                password:               "%ldap_driver_password%"
                bindRequiresDn:         true
                accountFilterFormat:    "%ldap_driver_account_filter_format%"
                tryUsernameSplit:       "%ldap_driver_try_username_split%"
                networkTimeout:         "%ldap_timeout%"
            user:
                baseDn:                 "%ldap_user_base_dn%"
                filter:                 "%ldap_user_filter%"
                # Specify ldap attributes mapping [ldap attribute, user object method]
                attributes:
                   # Username should be the first
                   - { ldap_attr: "%ldap_user_attr_username%",    user_method: setUsername }
                   - { ldap_attr: "%ldap_user_attr_mail%",        user_method: setEmail }
                   - { ldap_attr: "%ldap_user_attr_firstname%",   user_method: setFirstname }
                   - { ldap_attr: "%ldap_user_attr_lastname%",    user_method: setLastname }
```

Frequently, you need to pass complete dn for the LDAP service account username to connect.

**Comment by henry-geronimo** [comment]
Hi i've found the problem. the filter used to query the LDAP is (&(uid=test-user)) but i need it to be (&(sAMAccountName=test-user)).
I've been trying to change the config accountFilterFormat to (&(sAMAccountName=%s)) but it doesn't seem to trigger any change.
the filter created is always (&(uid=%s)) (ZendLdapDriver line 61)
When i force it (by directly editing the filter in the files) everything is working !


EDIT: OK !!! My bad ! in FR3DLdapBundle you could just set the userameAttribute with a config like this

```
    user:
        baseDn: '%ldap_base_dn%'
        usernameAttribute: sAMAccountName
```
Using your bundle i need to do it like this : 

```
    user:
      baseDn: '%ldap_base_dn%'
          attributes:
              - { ldap_attr: sAMAccountName, user_method: setUsername }
```

I don't really need to add a user_method because i have my own hydrator, but it's working anyway.
Everything seems to be working fine now. thank you !
